export const BROADCAST_QUEUE_NAME = 'broadcast';

export const TELEGRAM_BROADCAST_SCENE = 'TELEGRAM_BROADCAST_SCENE';
export const VK_BROADCAST_SCENE = 'VK_BROADCAST_SCENE';

export const DEFAULT_BROADCAST_HISTORY_LIMIT = 4;
export const DEFAULT_BROADCAST_JOB_DELAY_MS = 300;
export const DEFAULT_BROADCAST_JOB_CONCURRENCY = 1;
